<?php
use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>

<div class = "custom">
    <?php  if($block->getData("path_image")): ?>
        <div class = "custom-title">
            <?php if($block->getData("title")): ?>
                <h2><?=$block->escapeHtml($block->getData("title")) ?></h2>
            <?php endif;?>
        </div>
        <div class = "custom-logo">
            <img src = "<?= $block->escapeUrl($block->getViewFileUrl($block->getData('path_image'))) ?>"
            alt = "<?= $block->escapeHtmlAttr($block->getData('title'))?>" />
        </div>
    <?php endif; ?>
</div>

