<?php
/* @var Radicle\FirstModule\Block\Hello $block */
$authors =  $block->getAllAuthors();
?>

<!--The above validation alias will invoke JavaScript lib/web/mage/validation/validation.js which generally contains the logic of validation.-->
<form method = "post" name = "myForm" action = "<?php $block->getAddAuthorPostUrl() ?>"  data-mage-init='{"validation":{}}'>
    <fieldset>
        <div>
            <label for="Author"><?= __("Author") ?></label>
            <input type = "text" name = "author_name" id="author_name" required = "true"/>  <!--Method 1: Use Rule Name As an Attribute-->
        </div>
        <div>
            <label for="email"><?= __("Email") ?></label>
            <input class= "input-text required" type = "email" name = "email" id="email" /> <!--Method 2: Use Rule Name As Class Name-->
        </div>
        <div>
            <label for="description"><?= __("Description") ?></label>
            <input data-validate='{"required" : true,"custom-min-length" : true}' type = "text" name = "description" id="description"/>   <!--Method 3: Use “Data-Validate” Attribute -->
        </div>
        <div>
            <label for="store"><?= __("Store ID") ?></label>
            <input type = "number" name = "store_id" id="store_id" required/>
        </div>
        <div>
            <label for="Time"><?= __("Time occured") ?></label>
            <input type = "datetime-local" name = "time_occured" id="time_occured" required/>
        </div>
        <input type="submit" value="<?= __("Add Author") ?>" />
    </fieldset>
</form>
<hr/>

<?php if(count($authors) > 0) : ?>
<table border="1">
    <tr>
        <th><?= __("ID") ?></th>
        <th><?= __("Author") ?>
         <th><?= __("Email") ?></th>
        <th><?= __("Description") ?></th>
        <th><?= __("Store Id") ?></th>
        <th><?= __("Time") ?></th>
        <th><?= __("Customer Id") ?></th>
    </tr>
    <?php foreach ($authors as $author): ?>
        <tr>
            <td><?= $author->getId() ?>
            <td><?= $author->getAuthor_name() ?>
            <td><?= $author->getEmail() ?>
            <td><?= $author->getDescription() ?>
            <td><?= $author->getStore_id() ?>
            <td><?= $author->getTime_occured() ?>
            <td><?= $author->getData("Customer Id") ?>
        </tr>
    <?php endforeach; ?>
</table>
<?php else: ?>
    <h1><?= __("You have no authors yet :(") ?></h1>
<?php endif; ?>

<!--<script>-->
<!--    if ( window.history.replaceState ) {-->
<!--    window.history.replaceState( null, null, window.location.href );-->
<!--    }-->
<!--</script>-->


<!--Method #4 – Set Rule in data-mage-init Attribute of Form Tag-->
<label class="description"  data-mage-init='{
    "validation":{
        "rules": {
            "description": {
                "custom-min-length":true
            }
        }
    }
}'>


