<?php
/** @var Radicle\FirstModule\Block\Cms $block **/
?>

<h1>KNOCKOUTJS EXAMPLE!!!!!</h1>
<div id="custom-component" data-bind="scope:'customcomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#custom-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customcomponent": {
                        "component": "Radicle_FirstModule/js/custom-component"
                    }
                }
            }
        }
    }
    </script>
</div>


<div id = "custom-clock" data-bind="scope:'customclock'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type = "text/x-magento-init">
    {
        "#custom-clock": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customclock": {
                        "component": "Radicle_FirstModule/js/custom-clock"
                    }
                }
            }
        }
    }
    </script>
</div>

<div>
    <h3 style="text-align: center; text-decoration: underline">Radicle Author Information..</h3>
<?php
    $helper = $this->helper('Radicle\FirstModule\Helper\Data');
    $authors = json_decode($helper->getDetails(),true);
    ?>
</div>

<button id="button" style="text-align: center;margin-left:550px">
    <span><?= $block->escapeHtml(__('Show Authors')) ?></span>
</button>

<div id="modal" style="display: none">
    <div class="modal-body-content">
        <?php if(count($authors) > 0) : ?>
            <table border="1">
                <tr>
                    <th><?= __("ID") ?></th>
                    <th><?= __("Author") ?>
                    <th><?= __("Email") ?></th>
                    <th><?= __("Description") ?></th>
                    <th><?= __("Store Id") ?></th>
                    <th><?= __("Time") ?></th>
                    <th><?= __("Customer Id") ?></th>
                </tr>
                <?php foreach ($authors as $author): ?>
                    <tr>
                        <td><?= $author["id"] ?>
                        <td><?= $author["author_name"] ?>
                        <td><?= $author["email"] ?>
                        <td><?= $author["description"] ?>
                        <td><?= $author["store_id"] ?>
                        <td><?= $author["time_occured"] ?>
                        <td><?= $author["customer_id"] ?>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php else: ?>
            <h1><?= __("You have no authors yet :(") ?></h1>
        <?php endif; ?>

    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"     //js class like a component in react.
    ],function($, modal) {

        var options = {     //props
            type: 'popup',
            responsive: true,
            modalTitle : "Authors DataSet",
            title: 'Author Dataset',
            buttons: [{
                text: $.mage.__('Ok'),
                class: 'OK',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#modal'));    //options,targetElementPassed
        $("#button").click(function() {         //jquery
            $('#modal').modal('openModal');
            $("#modal").css("background-color", "lightgrey");
        });


        setTimeout(()=>{
            console.log("working");
            $.ajax({
                url: "https://demo.magento2.com/rest/V1/radicle",
                method: 'GET',
                success: function( result ) {
                    console.log(result);
                    // $( "#wiki" ).html( "<strong>" + String(result) + "</strong> degrees" );
                },
            });
        },1000)
    });
</script>
