<?php
namespace Mastering\SampleModule\Model\VirtualType;
class UpperCaseName extends \Mastering\SampleModule\Model\VirtualType\Name{
    public function getName(string $name): string
    {
        return strtoupper(parent::getName($name)); // TODO: Change the autogenerated stub
    }
}
